const myform = document.querySelector("#myForm")
const dissmiss = document.querySelector("#dissmiss")
const email = document.querySelector("#email")
const errorText = document.querySelector("#errorText")
const container = document.querySelector("#.container")
const successCard = document.querySelector(".success-card")
const emailText = document.querySelector("#emailtext")
const submitButton = document.querySelector(".submit-buttton")